In [12]:
!python -m spacy download en_core_web_lg  # Can do lg, takes awhile

     |████████████████████████████████| 827.9MB 1.1MB/s 
  Created wheel for en-core-web-lg: filename=en_core_web_lg-2.2.5-cp36-none-any.whl size=829180944 sha256=d68c62453078fb529b8f8294dc954b97b55443f658d2781cba2a50e66c592474
  Stored in directory: /tmp/pip-ephem-wheel-cache-r_3_a47n/wheels/2a/c1/a6/fc7a877b1efca9bc6a089d6f506f16d3868408f9ff89f8dbfc
Successfully built en-core-web-lg
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')


In [10]:
!wget https://raw.githubusercontent.com/LambdaSchool/DS-Unit-4-Sprint-1-NLP/main/requirements.txt
!pip install -r requirements.txt

--2020-11-17 16:58:00--  https://raw.githubusercontent.com/LambdaSchool/DS-Unit-4-Sprint-1-NLP/main/requirements.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137 [text/plain]
Saving to: ‘requirements.txt’

requirements.txt    100%[===================>]     137  --.-KB/s    in 0s      

2020-11-17 16:58:01 (5.14 MB/s) - ‘requirements.txt’ saved [137/137]

     |████████████████████████████████| 24.2MB 5.1MB/s 
     |████████████████████████████████| 1.6MB 51.6MB/s 
     |████████████████████████████████| 10.4MB 45.4MB/s 
     |████████████████████████████████| 7.1MB 41.7MB/s 
     |████████████████████████████████| 215kB 44.8MB/s 
     |████████████████████████████████| 2.2MB 46.3MB/s 
  Created wheel for pyLDAvis: filename=pyLDAvis-2.1.2-py2.py3-none-any.w

Cleaning Dataframe

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/kushyapp/cannabis-dataset/master/Dataset/Strains/strains-kushy_api.2017-11-14.csv')

In [3]:
df = df[['id','name','type','effects','ailment','flavor','location']]

In [4]:
df = df.dropna(how='any', subset=['effects', 'ailment'])

In [5]:
df['location'] = df['location'].fillna('-')
df['flavor'] = df['flavor'].fillna('-')

In [6]:
df.shape

(971, 7)

In [7]:
df.isnull().sum()

id          0
name        0
type        0
effects     0
ailment     0
flavor      0
location    0
dtype: int64

In [8]:
df.head(15)

id                  name  ...                 flavor        location
0    1                100 OG  ...                 Citrus               -
2    3                  A-10  ...          Citrus, Sweet               -
3    4         Acapulco Gold  ...         Earthy, Citrus               -
4    5     Afghani Bullrider  ...    Sweet, Pine, Earthy               -
5    6        Afghan Big Bud  ...        Lemon, Lavender               -
8    9               Afghani  ...    Earthy, Sweet, Pine               -
10  11              Afghooey  ...          Earthy, Sweet               -
11  12                 Afgoo  ...   Pine, Earthy, Citrus               -
12  13               Afgooey  ...           Earthy, Pine               -
17  18  Alaskan Thunder Fuck  ...           Earthy, Pine  Mt. Shasta, CA
19  20                 Aloha  ...          Sweet, Citrus               -
23  24          Amnesia Haze  ...  Citrus, Lemon, Earthy               -
24  25            Anesthesia  ...                 Earthy               -
26  27          Arabian Gold  ...                      -               -
34  35        BC Sweet Tooth  ...           Sweet, Honey               -

[15 rows x 7 columns]

NLP tokenizing on word columns

In [9]:
"""
Import Statements
"""

# Base
from collections import Counter
import re
 
import pandas as pd

# Plotting
import squarify
import matplotlib.pyplot as plt
import seaborn as sns

# NLP Libraries
import spacy
from spacy.tokenizer import Tokenizer
from nltk.stem import PorterStemmer

nlp = spacy.load("en_core_web_lg")
# Wrap it all in a function


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [10]:
# Wrap it all in a function
def get_lemmas(text):

    lemmas = []
    
    doc = nlp(text)
    
    # Something goes here :P
    for token in doc: 
        if ((token.is_stop == False) and (token.is_punct == False)) and (token.pos_ != 'PRON'):
            lemmas.append(token.lemma_)
    
    return lemmas

In [11]:
df.head(2)

id    name  ...         flavor location
0   1  100 OG  ...         Citrus        -
2   3    A-10  ...  Citrus, Sweet        -

[2 rows x 7 columns]

In [12]:
df['ailment'] = df['ailment'].astype(str)
df['effects'] = df['effects'].astype(str)

In [13]:
df.dtypes

id           int64
name        object
type        object
effects     object
ailment     object
flavor      object
location    object
dtype: object

In [14]:
STOP_WORDS = ['idk']

In [15]:
df['effects'] = df['effects'].str.lower()
df['ailment'] = df['ailment'].str.lower()
df['flavor'] = df['flavor'].str.lower()


In [16]:
def get_lemmas(text):

    lemmas = []
    
    doc = nlp(text)
    
    for token in doc: 
        if ((token.text.lower() not in STOP_WORDS) and (token.is_stop == False) and (token.is_punct == False)) and (token.pos_ != 'PRON'):
            lemmas.append(token.lemma_)
    
    return lemmas
    
df['effectsL'] = df.effects.apply(lambda x: get_lemmas(x))
df['ailmentL'] = df.ailment.apply(lambda x: get_lemmas(x))
df['flavorL'] = df.ailment.apply(lambda x: get_lemmas(x))


In [17]:
def tokenize(text):
    """Parses a string into a list of semantic units (words)

    Args:
        text (str): The string that the function will tokenize.

    Returns:
        list: tokens parsed out by the mechanics of your choice
    """
    
    tokens = re.sub('[^a-zA-Z 0-9]', '', text)
    tokens = tokens.lower().split()
    
    return tokens

In [87]:
#df['effectsL'] = df['effectsL'].replace("dry", "three")
df['lemmas'] = df['effectsL'] + df['ailmentL'] + df['flavorL']
df['lemmas'] = df['effectsL'] + df['ailmentL'] + df['flavorL']
df['text'] = df['effects'] + df['ailment'] + df['flavor']


In [19]:
df = df.reset_index()


In [20]:
df.head(5)

index  ...                                               text
0      0  ...                            focuseddepressioncitrus
1      2  ...  relaxed, happy, uplifted, energetic, sleepy, d...
2      3  ...  happy, euphoric, uplifted, relaxed, creative, ...
3      4  ...  uplifted, relaxed, happy, euphoric, dry mouth,...
4      5  ...  euphoric, happy, talkative, relaxed, sleepy, d...

[5 rows x 13 columns]

In [21]:
df['effects'].value_counts()

relaxed, sleepy, happy, euphoric, hungry, dry mouth, paranoid               7
relaxed, happy, euphoric, sleepy, uplifted, dry mouth, anxious              7
relaxed, sleepy, euphoric, happy, uplifted, dry mouth, paranoid             6
relaxed, happy, euphoric, sleepy, uplifted, dry mouth, paranoid, anxious    5
relaxed, sleepy, happy, euphoric, hungry, dry mouth, anxious                5
                                                                           ..
happy, energetic, euphoric, talkative, horny, dry mouth                     1
relaxed, happy, tingly                                                      1
euphoric, creative, uplifted, energetic, dry mouth, paranoid                1
sleepy, happy, relaxed, euphoric, tingly, dry mouth                         1
relaxed, creative, uplifted, happy, talkative, dry mouth, anxious           1
Name: effects, Length: 870, dtype: int64

In [22]:
# Object from Base Python
from collections import Counter

# The object `Counter` takes an iterable, but you can instaniate an empty one and update it. 
word_counts = Counter()

# Update it based on a split of each of our documents
df['ailmentL'].apply(lambda x: word_counts.update(x))

# Print out the 10 most common words
word_counts.most_common(30)

[('stress', 858),
 ('depression', 772),
 ('pain', 771),
 ('insomnia', 515),
 ('lack', 353),
 ('appetite', 353),
 ('nausea', 203),
 ('inflammation', 190),
 ('muscle', 188),
 ('spasm', 188),
 ('seizure', 7)]

In [23]:
# Object from Base Python
from collections import Counter

# The object `Counter` takes an iterable, but you can instaniate an empty one and update it. 
word_counts = Counter()

# Update it based on a split of each of our documents
df['effectsL'].apply(lambda x: word_counts.update(x))

# Print out the 10 most common words
word_counts.most_common(30)

[('happy', 830),
 ('dry', 820),
 ('mouth', 820),
 ('relaxed', 738),
 ('euphoric', 721),
 ('uplifted', 612),
 ('paranoid', 490),
 ('sleepy', 451),
 ('anxious', 408),
 ('creative', 279),
 ('energetic', 262),
 ('hungry', 229),
 ('focused', 184),
 ('tingly', 149),
 ('talkative', 138),
 ('horny', 90),
 ('focus', 24)]

In [24]:
df.head(2)

index  ...                                               text
0      0  ...                            focuseddepressioncitrus
1      2  ...  relaxed, happy, uplifted, energetic, sleepy, d...

[2 rows x 13 columns]

-

-Put into vector

-

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)

# Create a vocabulary and get word counts per document
# Similiar to fit_predict
dtm = tfidf.fit_transform(df)

# Print word counts

# Get feature names to use as dataframe column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())

# View Feature Matrix as DataFrame
dtm.head()

ailment  ailmentl  effects  effectsl  ...  lemmas  location  text  type
0      0.0       0.0      0.0       0.0  ...     0.0       0.0   0.0   0.0
1      0.0       0.0      0.0       0.0  ...     0.0       0.0   0.0   0.0
2      0.0       0.0      0.0       0.0  ...     0.0       0.0   0.0   0.0
3      0.0       0.0      0.0       0.0  ...     0.0       0.0   0.0   1.0
4      0.0       0.0      1.0       0.0  ...     0.0       0.0   0.0   0.0

[5 rows x 12 columns]

In [26]:
# Tunning Parameters

# Instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english', 
                        ngram_range=(1,2),
                        max_df=.97,
                        min_df=3,
                        tokenizer=tokenize)

# Create a vocabulary and get word counts per document
dtm = tfidf.fit_transform(df.text) # Similiar to fit_predict

# Print word counts

# Get feature names to use as dataframe column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())

# View Feature Matrix as DataFrame
dtm.head()

ammonia  anxious  anxious dry  ...  uplifted tingly  uplifteddepression  vanilla
0      0.0      0.0          0.0  ...              0.0                 0.0      0.0
1      0.0      0.0          0.0  ...              0.0                 0.0      0.0
2      0.0      0.0          0.0  ...              0.0                 0.0      0.0
3      0.0      0.0          0.0  ...              0.0                 0.0      0.0
4      0.0      0.0          0.0  ...              0.0                 0.0      0.0

[5 rows x 630 columns]

-

-k nearest neigbor

-

In [73]:
from sklearn.neighbors import NearestNeighbors

# Fit on DTM
nn = NearestNeighbors(n_neighbors=4, algorithm='kd_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                 radius=1.0)

In [74]:
nn.kneighbors([dtm.iloc[0].values])

(array([[0., 1., 1., 1.]]), array([[  0, 440, 399,  31]]))

In [75]:
For = [ """


pain

"""]
Tast = [ """


earthy

"""]


In [76]:
output = Tast + For

In [77]:
# Query for Sim of Random doc to BBC
new = tfidf.transform(output)

In [78]:
new

<2x630 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [79]:
nn.kneighbors(new.todense())


(array([[1.        , 1.06447526, 1.14309401, 1.19342835],
        [1.        , 1.26904738, 1.29291628, 1.29727485]]),
 array([[  0, 560, 851, 736],
        [  0, 668, 811, 433]]))

In [81]:
# Inspect Most relevant result
df['text'][668]

'relaxed, euphoric, tingly, sleepy, upliftedinflammation, pain, stressammonia'

In [88]:
df.iloc[668]['name']

'Dorit'

In [90]:
import pickle

In [92]:

# save the model to disk
filename = 'model.pickle'
pickle_model = open(filename, 'wb')
pickle.dump(nn, pickle_model)
pickle_model.close()


loaded_model = pickle.load(open(filename, 'rb'))
# some time later...
# load the model from disk
#loaded_model = pickle.load(open(filename, 'rb'))
#result = loaded_model.score(X_test, Y_test)
#print(result)

_

I think k search will work for what we want ^

_